In [13]:
#A single neuron with 4 inputs

In [14]:
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2


In [15]:
output=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2] + inputs[3]*weights[3]+bias)
print(output)


4.8


In [16]:
#Implementing a layer of neurons

In [17]:
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1.0]
weights2 = [0.5, -0.91, 0.26, -0.5] 
weights3 = [-0.26, -0.27, 0.17, 0.87] 

bias1=2
bias2 = 3 
bias3 = 0.5 

In [18]:
outputs = [ 
        # Neuron 1: 
        inputs[0]*weights1[0] + 
        inputs[1]*weights1[1] + 
        inputs[2]*weights1[2] + 
        inputs[3]*weights1[3] + bias1, 
 
        # Neuron 2: 
        inputs[0]*weights2[0] + 
        inputs[1]*weights2[1] + 
        inputs[2]*weights2[2] + 
        inputs[3]*weights2[3] + bias2, 
 
        # Neuron 3: 
        inputs[0]*weights3[0] + 
        inputs[1]*weights3[1] + 
        inputs[2]*weights3[2] + 
        inputs[3]*weights3[3] + bias3] 
 
print(outputs) 

[4.8, 1.21, 2.385]


In [19]:
#Implementing NN using loop to scale and handle dynamically-sized inputs and layers

In [20]:
inputs = [1, 2, 3, 2.5] 
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]] 
biases = [2, 3, 0.5] 

layer_output=[]
for input_weight,input_bias in zip(weights,biases):
    n_output=0
    for n_input,weight in zip(inputs,input_weight):
        n_output=n_input*weight + n_output
    n_output=n_output+input_bias
    layer_output.append(n_output)

In [21]:
#Single Neuron using dot product

In [22]:
import numpy as np
inputs = [1, 2, 3, 2.5] 
weights=[0.2,0.8,-0.5,1.0]
bias=2

In [24]:
outputs=np.dot(weights,inputs) + bias
print(outputs)

4.8


In [25]:
#Implementing layer of neurons using dot product

In [27]:
inputs = [1, 2, 3, 2.5] 
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]] 
biases = [2, 3, 0.5]

layer_outputs=np.dot(weights,inputs)+biases
print(layer_outputs)

[4.8   1.21  2.385]


In [28]:
#A Layer of Neurons & Batch of Data w/ NumPy 

In [30]:
inputs = [[1, 2, 3, 2.5],
          [2,5,-1,2],
          [-1.5,2.7,3.3,-0.8] ]
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]] 
biases = [2, 3, 0.5]
outputs=np.dot(inputs,np.array(weights).T)+biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
